version: '3.8'

services:
  marketplace-backend:
    build: ./marketplace
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
    networks:
      - my_network

  microservice-food-waste-backend:
    build: ./microservice_food_waste
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
    networks:
      - my_network

  microservice-sensor-plant:
    build: ./microservice_sensor_plant
    ports:
      - "8082:8082"
    networks:
    - my_network

networks:
  my_network:
    driver: bridge